# Generated by Django 5.0.3 on 2024-03-30 04:25

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        default=django.contrib.auth.models.User,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="para_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(db_index=True, max_length=100)),
                (
                    "para",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.paragraph"
                    ),
                ),
            ],
            options={
                "unique_together": {("text", "para")},
            },
        ),
    ]
